### ISSUE TITLE
[TRACKER] C# Code checklist

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot-docs#1302]
Recently I've been doing work on adding C# code examples to the documentation using code tabs. Since more people are joining I've made this list so we don't accidentally work on the same pages and waste time. This list is every page with code examples, excluding the ones in the scripting section since those are language specific pages.

Whenever you are working on a page or section please open a GitHub issue so we know. And whenever deciding what to work on check for existing GitHub issues. 

Additionally, not all pages are up to date for version 3.0 of Godot. You can check this [list](https://github.com/godotengine/godot-docs/issues/946#issuecomment-377623582) to see what pages are up to date for 3.0. Pages that aren't up to date may contain outdated GDScript making it impossible to translate to C#. If you have the knowledge to update a page then by all means go ahead.

## Step by step
- [x] Scripting
- [x] Scripting continued
- [x] Your First Game
- [x]  Exporting
- [x] Control the game's UI with code #1365 
- [x] Resources #1380 
- [x] SceneTree
- [x] Singletons (AutoLoad) #1382 

## Project Workflow
- [ ] Importing 3D Scenes
- [ ] Exporting for the web

### 2D
- [x] Viewport and canvas transforms #1331 
- [x] Custom drawing in 2D #1368 
- [x] 2D Movement Overview
### 3D
- [x] Using transforms for 3D games in Godot #1392 
- ~~Working with 3D skeletons~~ (dropped)
- ~~Inverse kinematics~~ (dropped)
- [ ] FPS tutorial
### Physics
- [x] Physics introduction #1314 
- [x] Rigid Body #1314
- [x] Using KinematicBody 2D #1362 
- [x] Ray-casting #1314 
- [x] KinematicCharacter(2D)
### Math
- [x] Vector math #1313 
- [x] Advanced Vector Math #1319 
- [x] Matrices and transforms #1321 
### Inputs
- [x] InputEvent
- [x] Mouse and input coordinates
- [x] Customizing mouse cursor
### I/O
- [ ] Background Loading
- [x] Saving Games #1327 
- [x] Encrypting save games
### Internationalization
- [ ] Internationalizing games
### GUI
- [x] GUI Skinning
- [x] Custom GUI controls #1383 
### Viewports
- [ ] Viewports
### Networking
- [ ] High level multiplayer
- [ ] Making HTTP requests
### VR
- [x] An AR/VR Primer for Godot
- [ ] VR starter tutorial
- [ ] Developing for Oculus Quest
### Plugins
- [x] Making Plugins
- [ ] Import Plugins
### Platform-specific
- [ ] android in-app purchases
- [ ] Services for ios
### Multi-threading
- [ ] Using multiple threads
- [ ] Thread safe APIs
### Optimization
- [ ] Optimization using servers
- [x] Optimization using MultiMeshes
### Miscellaneous
- [x] Handling quit requests #1312 
- [x] Pausing Games #1312

**Comment by paulloz** [comment]
Hi, I'm currently working on the pages under Tutorials/Physics ☺

**Comment by paulloz** [comment]
You can tick **Physics introduction**, **Ray-casting**, **Handling quit requests** and **Pausing Games**.

**Comment by exts** [comment]
Mark off ` Control the game's UI with code` with https://github.com/godotengine/godot-docs/pull/1365

**Comment by imekon** [comment]
What about path finding or Navigation2D?

**Comment by exts** [comment]
@imekon not sure what you're asking as this thread is about converting currently existing docs with gdscript examples and giving c# alternative examples.

If you're requesting docs, create a new issue.

**Comment by barrrettt** [comment]
The subjects of the threads I think they need a separate and simple example.

**Comment by mhilbrunner** [comment]
As there hasn't been much activity here anymore and most of those are now done, I'll close this in favor of opening more specific issues/PRs if we still miss C# support somewhere.

Thanks for all who contributed!
