### ISSUE TITLE
[TRACKER] Docs updates for 3.1 release

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot-docs#1603]
There a lot of new and updated features for 3.1 that need to be addressed.

- [ ] **New Features**
    - [x] GDScript type hinting
    - [ ] Visual Shader editor
    - [ ] AnimatedTexture
    - [ ] New Animation Tree + State Machine ([announcement](https://godotengine.org/article/godot-gets-new-animation-tree-state-machine))
    - [ ] New advanced physics features (Inverse Kinematics, Soft Body, ...)

- [ ] **Updated features/descriptions**
    - **Step by step**
        - [ ] New "create root node" feature
    - [ ] KinematicBody changes ([announcement](https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody))
    - [ ] New animation panel
    - [ ] Networking
    - [ ] New Inspector
        - [ ] update many screenshots

- [ ] API Reference (check doctool for missing descriptions)

Many more - please add to this list so that we can track as we did in #946

**Comment by PetePete1984** [comment]
As discussed on Discord, I'll tackle transforming the 2.1 Space Shooter demo to 3.1 soon, both updating the demo project as well as extending the docs.
Since I'll want to use the type hinting (to learn and to teach), I'm not sure if an entry in the Tutorials > 2D section is the right place for it, or if we should start a Tutorials > Scripting section, sort of as a hands-on extension to the Getting Started > Scripting area.
We do have a great "all the things" starter tutorial in Dodge the Creeps already and the Space Shooter technically doesn't bring many new concepts to the table, so its focus could be shifted to semi-advanced scripting - it could include signals & groups, singletons, pulling in other classes via preloads, and finally some dictionary, timer and yield magic for enemy patterns.
I might split that workload into a flat conversion of the existing demo and then an extended tutorial building off of it, though - Space Shooter and Space Shooter Deluxe, heh

**Comment by vnen** [comment]
I'm working on the GDScript docs BTW.

**Comment by cbscribe** [comment]
> I'm working on the GDScript docs BTW

OK, cool - I was going to copy and paste your excellent announcement text to use as the basis of the doc anyway.

**Comment by clayjohn** [comment]
Should we add the tutorials from [the Patreon](https://www.patreon.com/posts/results-and-17595598) to this as well?

**Comment by vnen** [comment]
@clayjohn tutorials requested from Patreon have their own schedules, they are not tied to a particular release.

**Comment by clayjohn** [comment]
Ah, I see. That makes sense. Better not mix it in then.

**Comment by mhilbrunner** [comment]
I added networking (many improvements, will try to take on this one ast I was involved) and physics (IK, soft bodies, ...).

Also, some of the 3.1 changes have far-reaching consequences for many docs and tutorials. The new inspector invalidates many screenshots that need to be updated.

Features like typed GDScript and the improved 'extends'/new 'class' functionality need to be documented too.

**Comment by ricardoalcantara** [comment]
Hey could you please provide me any hint on how to play Animations using the New Animation Tree + State Machine? I built a StateMachine but I have no clue how to play it in code.

**Comment by ZX-WT** [comment]
- [ ] 2d mesh #1766 

- [ ] softbody #1665

- [ ] ik #1665

- [ ] csg tools #1414

- [ ] ragdoll #1763 

Above are some features that need basic doc, they are now as news on the godot website, let's move it into the docs and improve it if possible

**Comment by nicoechaniz** [comment]
Microphone support as implemented here should be documented?

https://github.com/godotengine/godot/pull/19106
