### ISSUE TITLE
[TRACKER] GLES2 and GLES3 Differences

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot-docs#2205]
We should track the differences between GLES2 and GLES3 and ideally have something in the docs prior to the release of 3.1 for users to turn to. I have added the difference I can think of off the top of my head, but I am sure that there are more so please add to this issue so we can put a document together soon.

- [x] No Particles in GLES2 (Use CPUParticles instead)
- [x] No MipMaps on ``SCREEN_TEXTURE`` in GLES2. See https://github.com/godotengine/godot/pull/26044
- [x] Color space is different between GLES2 and GLES3. Document usage of ``OUTPUT_IS_SRGB``. See https://github.com/godotengine/godot/issues/25142
- [x] Reduced SpatialMaterial features in GLES2 (Refraction, subsurf, anisotropy, clearcoat, depth)
- [x] Reduced Environment features in GLES2 (auto_exposure, tonemap, ss reflections, ssao, dof blur, glow, adjustment) (only has sky, ambient, and fog)

- [x] GIProbe does not work in GLES2, using lightmaps (BakedLightmap) is recommended.

- [x] Contact shadows also do not work in GLES2

- [x] Reading from depth (DEPTH_TEXTURE) in the shader, does not work on every hardware. On old mobile hardware this is most likely not supported.

- [x] Performance scales poorly in GLES2 with several lights, as each is processed in a separate render pass (in opposition to GLES3 which is all done in a single pass).

- [x] On mobile, GLES2 requires ETC texture compression, while GLES3 requires ETC2. Showing how to enable ETC compression in the project settings if exporting to mobile would be nice.

- [x] Blend Shapes do not work on GLES2 (could be made to work eventually, but it's a lot of work and wont be fast).

- [x] GLES2 besides being linear color, is not HDR capable. This could be noted probably.

- [x] Some GLSL functions are only in GLESS3 (TextureSize for example). Should be documented in the shading doc and mentioned here

**Comment by StraToN** [comment]
Is this list exhaustive ?

**Comment by clayjohn** [comment]
Not necessarily. The goal is to have an exhaustive list, but i may have missed something. If you have anything that should be added, i would be happy to do so.

**Comment by StraToN** [comment]
Unfortunately, I don't :'( That's why I asked. 
If @godotengine/documentation team is ok to keep this as a start, it can indeed be useful to users who wonder what actual differences lie between the 2 versions, so much important that we need to keep both of them in Godot :)

**Comment by clayjohn** [comment]
If you know of any differences please add them! I had hoped this issue would get more attention, i also reached out on the discord but no one responded.

**Comment by clayjohn** [comment]
List of things from reduz:
GIProbe does not work in GLES2, using lightmaps (BakedLightmap) is recommended.
-Contact shadows also do not work in GLES2
-Reading from depth (DEPTH_TEXTURE) in the shader, does not work on every hardware. On old mobile hardware this is most likely not supported.
-Performance scales poorly in GLES2 with several lights, as each is processed in a separate render pass (in opposition to GLES3 which is all done in a single pass).
-On mobile, GLES2 requires ETC texture compression, while GLES3 requires ETC2. Showing how to enable ETC compression in the project settings if exporting to mobile would be nice.
-Blend Shapes do not work on GLES2 (could be made to work eventually, but it's a lot of work and wont be fast).
-GLES2 besides being linear color, is not HDR capable. This could be noted probably.

**Comment by akien-mga** [comment]
Thanks for your work on documenting all these differences!

Seems done now, so closing.
