### ISSUE TITLE
[TRACKER] Document new features in Godot 3.5

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot-docs#5797]
We now got a shiny 3.5 docs branch to document changes in Godot 3.5.
See the changelogs [here (by author)](https://downloads.tuxfamily.org/godotengine/3.5/beta4/Godot_v3.5-beta4_changelog_authors.txt) and [here (all commits)](https://downloads.tuxfamily.org/godotengine/3.5/beta4/Godot_v3.5-beta4_changelog_chrono.txt).

Calinou started updating the features page in https://github.com/godotengine/godot-docs/pull/5722.

- [x] OccluderShapePolygon: https://github.com/godotengine/godot-docs/pull/5795
- [x] 3D navigation server: https://github.com/godotengine/godot-docs/pull/5800
- [x] Physics Interpolation: https://github.com/godotengine/godot-docs/pull/5801
- [x] Material overlays: https://github.com/godotengine/godot-docs/pull/5826

Feel free to edit / comment.

**Comment by skyace65** [comment]
Just made a PR for the 3D navigation server.

**Comment by skyace65** [comment]
Made a PR for theme type variations (#5830). It's for the master branch but should be cherrypickable.

**Comment by skyace65** [comment]
Made a PR for scene unique nodes (5831). It's for the master branch but should be cherrypickable.

**Comment by skyace65** [comment]
Made a PR for Label3D and text mesh (#5847).
