### ISSUE TITLE
Add a contributor checklist for godot-doc contributions

### ISSUE THREAD

**Issue by StripedMonkey** [godotengine/godot-docs#9193]
I have been off and on working towards some documentation for the manual's "asset pipeline" section, and I have felt that the contribution resources for documentation specifically are rather confusing and scattered. Part of what I think would help significantly with my (and perhaps others) confidence when trying to make contributions is a checklist for what I need to do before making a contribution.

The idea here isn't to replace the existing documentation on contributions, but to make it easier for everyone to validate their own work before submitting for review. Some things are hard or outright missing from the docs, and I believe a checklist can help with exposing areas that need work, or at least making them more accessible to new contributors.

Below is a brief (incomplete) example of the kinds of things I'm hoping to see in such a checklist. Ideally these should be elaborated elsewhere in the docs, but it provides a summary instead of requiring a thorough reading of the entire documentation beforehand. Certain things here are additions I know are not mentioned in the docs, but have come up in conversation in the Godot Docs #documentation chat (redirects and hard line wrapping).

---

## General content checks

- [ ] The Writing and Content Guidelines have been read and understood
  - [ ] No unnecessary adjectives
  - [ ] No use of banned words
  - [ ] Only use explicit references
- [ ] When renaming pages, ensure that the old pages have a corresponding redirect in `_tools/redirects/redirects.csv` to the new page.
- [ ] Ensure consistent use of common vocabulary for interface locations, tools, etc.
- [ ] Content is hard-wrapped in source to between 80 and 100 characters

## Image checks

- [ ] Images should be constrained to at most 1080p

## Renames and reorganization

- [ ] Any document pages which have been moved or renamed need have `redirects.csv` updated accordingly.

## Code sample checks

- [ ] no `foo`/`bar`/`baz` names over real-world names
- [ ] prefer dynamic typing over static typing
- [ ] use explicit return types and arguments
